name: Build Windows EXE

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 30  # 添加超时限制

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pillow pandas openpyxl pdf2image reportlab PyPDF2 numpy pyinstaller

      - name: Download Poppler
        shell: powershell
        run: |
          Invoke-WebRequest -Uri "https://github.com/oschwartz10612/poppler-windows/releases/download/v24.08.0-0/Release-24.08.0-0.zip" -OutFile "poppler.zip"
          Expand-Archive -Path "poppler.zip" -DestinationPath "poppler_temp"
          New-Item -ItemType Directory -Force -Path "poppler"
          Copy-Item "poppler_temp/poppler-24.08.0/Library/bin/*" -Destination "poppler/" -Recurse
          Remove-Item "poppler.zip"
          Remove-Item "poppler_temp" -Recurse

      - name: Build with PyInstaller
        run: |
          pyinstaller --clean --noconfirm `
            --name="PDFWatermark" `
            --windowed `
            --onedir `
            --add-binary="poppler\pdftoppm.exe;." `
            --add-binary="poppler\pdfinfo.exe;." `
            --add-binary="poppler\pdftocairo.exe;." `
            --add-binary="poppler\pdfimages.exe;." `
            --hidden-import="openpyxl" `
            --hidden-import="openpyxl.styles" `
            --hidden-import="openpyxl.styles.stylesheet" `
            --hidden-import="pandas.io.excel._openpyxl" `
            --hidden-import="pdf2image" `
            --copy-metadata="pandas" `
            --copy-metadata="openpyxl" `
            src/app_main.py

      - name: Test build output
        shell: powershell
        run: |
          Write-Host "Checking output files..."
          if (Test-Path "dist/PDFWatermark/PDFWatermark.exe") {
            Write-Host "✓ Main executable found"
          }
          if (Test-Path "dist/PDFWatermark/pdftoppm.exe") {
            Write-Host "✓ Poppler tools found"
          }
          Get-ChildItem "dist/PDFWatermark" | Select-Object Name, Length | Select-Object -First 20

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PDFWatermark-Windows
          path: dist/PDFWatermark/**
