name: Build Windows EXE

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        shell: bash
        run: |
          python -m pip install --upgrade pip wheel setuptools
          pip install -r requirements.txt pyinstaller

      - name: Download Poppler Windows binaries
        shell: powershell
        run: |
          # 下载预编译的 Poppler Windows 二进制文件
          Invoke-WebRequest -Uri "https://github.com/oschwartz10612/poppler-windows/releases/download/v24.08.0-0/Release-24.08.0-0.zip" -OutFile "poppler.zip"
          Expand-Archive -Path "poppler.zip" -DestinationPath "poppler_temp"
          New-Item -ItemType Directory -Force -Path "poppler"
          Copy-Item "poppler_temp/poppler-24.08.0/Library/bin/*" -Destination "poppler/" -Recurse
          Remove-Item "poppler.zip"
          Remove-Item "poppler_temp" -Recurse

      - name: Build with PyInstaller
        shell: bash
        run: |
          python -m PyInstaller \
            --name="PDFWatermark" \
            --windowed \
            --onedir \
            --add-data="poppler;poppler" \
            --hidden-import="openpyxl" \
            --hidden-import="pandas.io.excel._openpyxl" \
            --clean \
            src/app_main.py

      - name: Test executable
        shell: powershell
        run: |
          # 检查生成的文件
          Get-ChildItem "dist/PDFWatermark" -Recurse | Select-Object -First 20
          
          # 检查 Poppler 文件
          if (Test-Path "dist/PDFWatermark/poppler/pdftoppm.exe") {
            Write-Host "✓ Poppler tools found in output"
          } else {
            Write-Host "✗ Poppler tools missing!"
          }

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PDFWatermark-Windows
          path: dist/PDFWatermark/**
